networks:
  crm-network:
    driver: bridge

services:
  brasedu-crm-api:
    build: .
    container_name: brasedu-crm-backend
    ports:
      - "8080:8080"
    networks:
      - crm-network

  brasedu-crm-db:
    container_name: brasedu-crm-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Crm@1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - crm-network
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/continue.sql:/docker-entrypoint-initdb.d/continue.sql
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr &
        pid=\$!;
        sleep 20;
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Crm@1234' -C -i docker-entrypoint-initdb.d/init.sql || true;
        sleep 30;
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Crm@1234' -C -i docker-entrypoint-initdb.d/continue.sql || true;
        wait \$pid
      "


volumes:
  sqlserver_data: